title: Louise Schaub
description: Personal website and portfolio

url: "https://louiseschaub.github.io"

theme: Cayman theme

markdown: kramdown

author:
  name: Louise Schaub

github_username: louiseschaub

header_pages:
  - index.md
  - about.md
